config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'search', to: 'search#index'
  resources :pictures
  root 'animes#index'

  resources :animes do
    resources :comments
  end
end

app/models/anime.rb
# frozen_string_literal: true

class Anime < ApplicationRecord
  include Visible
  has_rich_text :body
  has_many :comments, dependent: :destroy
  has_one :action_text_rich_text,
          class_name: 'ActionText::RichText',
          as: :record
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  include Visible
  has_rich_text :body
  belongs_to :anime
end

app/models/concerns/visible.rb
# frozen_string_literal: true

module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/picture.rb
# frozen_string_literal: true

class Picture < ApplicationRecord
  has_rich_text :body
end

app/controllers/animes_controller.rb
# frozen_string_literal: true

class AnimesController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin', except: %i[index show]

  def index
    @animes = Anime.all
  end

  def show
    @anime = Anime.find(params[:id])
  end

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)

    if @anime.save
      redirect_to @anime
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @anime = Anime.find(params[:id])
  end

  def update
    @anime = Anime.find(params[:id])

    if @anime.update(anime_params)
      redirect_to @anime
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def anime_params
    params.require(:anime).permit(:title, :body, :status)
  end

  def pin_params
    params.require(:pin).permit(:title, :body, :image, pictures: [])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_query

  def set_query
    @query = Anime.ransack(params[:q])
    @posts = @query.result(distinct: true)
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin', only: :destroy

  def create
    @anime = Anime.find(params[:anime_id])
    @comment = @anime.comments.create(comment_params)
    redirect_to anime_path(@anime)
  end

  def destroy
    @anime = Anime.find(params[:anime_id])
    @comment = @anime.comments.find(params[:id])
    @comment.destroy
    redirect_to anime_path(@anime), status: :see_other
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true

class PicturesController < ApplicationController
  before_action :set_picture, only: %i[show edit update destroy]

  # GET /pictures or /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1 or /pictures/1.json
  def show; end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit; end

  # POST /pictures or /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to picture_url(@picture), notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1 or /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to picture_url(@picture), notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1 or /pictures/1.json
  def destroy
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_picture
    @picture = Picture.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def picture_params
    params.require(:picture).permit(:title)
  end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  def index
    @query = Anime.ransack(params[:q])
    @animes = @query.result(distinct: true)
  end
end

app/helpers/animes_helper.rb
# frozen_string_literal: true

module AnimesHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/pictures_helper.rb
# frozen_string_literal: true

module PicturesHelper
end

app/helpers/search_helper.rb
# frozen_string_literal: true

module SearchHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/animes/_form.html.erb
<div class="main-banner">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 align-self-center">
        <div class="header-text">
          <%= form_with model: anime do |form| %>
            <div>
              <h1><%= form.label :title %><br></h1>
              <%= form.text_field :title %>
              <% anime.errors.full_messages_for(:title).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>

            <div>
              <h1>Body</h1>
              <%= form.rich_text_area :body %><br>
              <% anime.errors.full_messages_for(:body).each do |message| %>
                <div><%= message %></div>
              <% end %>
            </div>



            <div>
              <h1>Status</h1>

              <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
            </div>

            <div>
              <%= form.submit %>
            </div>
          <% end %>
        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/animes/edit.html.erb
<div class="page-heading normal-space">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2>Submission Edit</h2>
      </div>
    </div>
  </div>
</div>

<%= render "form", anime: @anime %>

app/views/animes/index.html.erb
<html lang="en">

<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="../../assets/stylesheets/fontawesome.css">
<link rel="stylesheet" href="/blog/app/assets/stylesheets/owl.css">
<link rel="stylesheet" href="../../assets/stylesheets/animate.css">
<link rel="stylesheet"href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
<link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


<!-- ***** Main Banner Area Start ***** -->
<div class="main-banner">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 align-self-center">
        <div class="header-text">
          <h6>Anime Love</h6>
          <h2>DISCUSS, DEBATE & THEORIZE TOP ANIMES.</h2>
          <p>Come join our discussion about our most beloved anime! From the most under-rated anime to the most popular airing anime! All types of people are here to join in on what you like and dislike about your favourite anime!</p>
        </div>
      </div>
      <div class="col-lg-5 offset-lg-1">
            <a class="twitter-timeline" data-lang="en" data-width="500" data-height="500" data-theme="dark" href="https://twitter.com/Crunchyroll?ref_src=twsrc%5Etfw">Tweets by Crunchyroll</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>          </div>
      </div>
    </div>
  </div>
</div>
<!-- ***** Main Banner Area End ***** -->
<div class="categories-collections">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="categories">
          <div class="row">
            <div class="col-lg-12">
              <div class="section-heading">
                <div class="line-dec"></div>
                <h2>Browse Through Our Most Discussed <em>Anime</em> Here.</h2>
              </div>
            </div>
            <div class="col-lg-2 col-sm-6">
              <div class="item">
                <div class="icon">
                  <%= image_tag 'Chainsaw Man.jpg' %>
                </div>
                <h4>Chainsaw Man</h4>
                <div class="icon-button">
                  <a href="/animes/1"><i class="fa fa-angle-right"></i></a>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-sm-6">
              <div class="item">
                <div class="icon">
                  <%= image_tag 'one-piece-merged-volumes-covers.jpg' %>
                </div>
                <h4>ONE PIECE</h4>
                <div class="icon-button">
                  <a href="/animes/8"><i class="fa fa-angle-right"></i></a>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-sm-6">
              <div class="item">
                <div class="icon">
                  <%= image_tag 'Bleach.jpg' %>
                </div>
                <h4>BLEACH: Thousand-Year Blood War</h4>
                <div class="icon-button">
                  <a href="/animes/11"><i class="fa fa-angle-right"></i></a>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-sm-6">
              <div class="item">
                <div class="icon">
                  <%= image_tag 'The Eminence in Shadow.jpg' %>
                </div>
                <h4>The Eminence in Shadow</h4>
                <div class="icon-button">
                  <a href="/animes/12"><i class="fa fa-angle-right"></i></a>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-sm-6">
              <div class="item">
                <div class="icon">
                  <%= image_tag 'Shinobi no Ittoki.jpg' %>
                </div>
                <h4>Shinobi no Ittoki</h4>
                <div class="icon-button">
                  <a href="/animes/13"><i class="fa fa-angle-right"></i></a>
                </div>
              </div>
            </div>
            <div class="col-lg-2 col-sm-6">
              <div class="item">
                <div class="icon">
                  <%= image_tag 'My-Hero-Academia-Poster.jpg' %>
                </div>
                <h4>My Hero Academia Season 6</h4>
                <div class="icon-button">
                  <a href="/animes/14"><i class="fa fa-angle-right"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

      </body>
</html>

app/views/animes/new.html.erb
<div class="page-heading normal-space">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2>Have a Submission? Do it below!</h2>
      </div>
    </div>
  </div>
</div>
<%= render "form", anime: @anime %>

app/views/comments/_comment.html.erb
<% unless comment.archived? %>
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to "Destroy Comment", [comment.anime, comment], data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>
  </p>

<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ @anime, @anime.comments.build ] do |form| %>

  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.rich_text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
  <p>
    <%= form.label :status %><br>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </p>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

</head>

<body>


<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <nav class="main-nav">
          <!-- ***** Logo Start ***** -->
            <a href="/animes/" class="logo">
              <img src="/assets/love anime logo.jpg">

          </a>
          <!-- ***** Logo End ***** -->
          <!-- ***** Menu Start ***** -->
          <ul class="nav">
            <li><a <%= link_to "Home", {controller: "animes", action: "index"}%></a></li>
            <li><a <%= link_to "Submit", new_anime_path%></a></li>
            <li><a <%= link_to "Search Page", search_path, method: :get%></a></li>
          </ul>
          <a class='menu-trigger'>
            <span>Menu</span>
          </a>
        </nav>
      </div>
    </div>
  </div>
</header>

<%= yield %>




</body>
</html>

app/views/pictures/_form.html.erb
<%= form_with(model: picture) do |form| %>
  <% if picture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
        <% picture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pictures/_picture.html.erb
<div id="<%= dom_id picture %>">
  <p>
    <strong>Title:</strong>
    <%= picture.title %>
  </p>

</div>

app/views/pictures/edit.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pictures</h1>

<div id="pictures">
  <% @pictures.each do |picture| %>
    <%= render picture %>
    <p>
      <%= link_to "Show this picture", picture %>
    </p>
  <% end %>
</div>

<%= link_to "New picture", new_picture_path %>

app/views/pictures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pictures</h1>

<div id="pictures">
  <% @pictures.each do |picture| %>
    <%= render picture %>
    <p>
      <%= link_to "Show this picture", picture %>
    </p>
  <% end %>
</div>

<%= link_to "New picture", new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render "form", picture: @picture %>

<br>

<div>
  <%= link_to "Back to pictures", pictures_path %>
</div>

app/views/pictures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @picture %>

<div>
  <%= link_to "Edit this picture", edit_picture_path(@picture) %> |
  <%= link_to "Back to pictures", pictures_path %>

  <%= button_to "Destroy this picture", @picture, method: :delete %>
</div>

app/views/search/_form.html.erb
<%= search_form_for @query, url: search_path do |f| %>
  <%= f.search_field :title_or_action_text_rich_text_body_cont, placeholder: "Search..." %>
  <%=f.submit "Search!", class:"btn btn-outline-success" %>
<% end %>

app/views/search/index.html.erb
<div class="page-heading normal-space">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h2>Current Submitted List!</h2>
      </div>
    </div>
  </div>
</div>
  <div class="main-banner">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 align-self-center">
          <div class="header-text">
  <h1 class="text-center"><%= pluralize(@animes.count, "Result") %></h1>

  <%= render 'search/form' %>

  <div class ="container">
    <table class="table table-dark table-striped">
      <thread>
        <tr>
          <th><%= sort_link(@query, :title, "Title", default_order: :asc) %></th>
          <th><%= sort_link(@query, :body, "About Anime") %></th>
        </tr>
      </thread>

      <tbody>
      <%@animes.each do|animes| %>
        <tr>
          <td><%= link_to animes.title, animes %></td>
          <td><%= animes.body.to_plain_text.truncate(100).strip.gsub(/(\(|\[).+(\)|\])/, '')%></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>